#!/usr/bin/python3

import sys
from parse import parse_args
from compute import compute
from average import average


def execute():
    args = parse_args()
    if len(sys.argv) == 3:
        compute(args.n, args.k)
    elif len(sys.argv) == 2:
        average(args.d)
    else:
        exit(84)


try:
    execute()
except:
    exit(84)
